
server.port: 8082

spring:
    datasource:
        url: "jdbc:mysql://localhost:3306/calc"
        username: root
        password: UbPXaZM4sS2yl4VcXyG8
#Hibernate
    jpa:
        properties:
            hibernate: 
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                format_sql: true
#Hibernate auto ddl
        hibernate: 
            ddl-auto: update
#JPA
        show-sql: false
        generate-ddl: false
    web:
        resources:
            cache:
                cachecontrol:
                    cache-public: true

logging:
    level:
        org:
            hibernate:
                SQL: error
                type: error

 

management.endpoints.web.exposure.include: "*"
