server.port: 8082

spring:
    batch:
        job:
            enabled: true
        initialize-schema: always
    datasource:
        url: jdbc:h2:mem:spring_batch
        username: sa
        password: password
        driverClassName: org.h2.Driver
    data:
        mongodb:
            database: calculation-service
            
