spring:
  cloud:
    gateway:
      routes:
      - id: brand-route
        uri: lb://BRANDSERVICE
        predicates:
        - Path=/brands/**
        - Paht=/filters/**
        filters:
        - AddRequestHeader=X-Tenant,acme
        - AddResponseHeader=X-Genre,webCalc
      - id: product-route
        uri: lb://PRODUCTSERVICE
        predicates:
        - Path=/products/**
        filters:
        - AddRequestHeader=X-Tenant,acme
        - AddResponseHeader=X-Genre,webCalc
      - id: model-route
        uri: lb://MODELSERVICE
        predicates:
        - Path=/models/**
        filters:
        - AddRequestHeader=X-Tenant,acme
        - AddResponseHeader=X-Genre,webCalc
      - id: engine-route
        uri: lb://ENGINESERVICE
        predicates:
        - Path=/engines/**
        filters:
        - AddRequestHeader=X-Tenant,acme
        - AddResponseHeader=X-Genre,webCalc
      - id: calculation-route
        uri: lb://CALCULATIONSERVICE
        predicates:
        - Path=/calculation/**
        filters:
        - AddRequestHeader=X-Tenant,acme
        - AddResponseHeader=X-Genre,webCalc