spring:
  cloud:
    gateway:
      routes:
      - id: brand-route
        uri: lb://BRANDSERVICE
        predicates:
        - Path=/api/v1/brands/**
        filters:
        - AddRequestHeader=X-Tenant,acme
        - AddResponseHeader=X-Genre,fanstasy
      - id: product-route
        uri: lb://PRODUCTSERVICE
        predicates:
        - Path=/api/v1/products/**
        filters:
        - AddRequestHeader=X-Tenant,acme
        - AddResponseHeader=X-Genre,fanstasy
      - id: model-route
        uri: lb://MODELSERVICE
        predicates:
        - Path=/api/v1/models/**
        filters:
        - AddRequestHeader=X-Tenant,acme
        - AddResponseHeader=X-Genre,fanstasy
      - id: engine-route
        uri: lb://ENGINESERVICE
        predicates:
        - Path=/api/v1/engines/**
        filters:
        - AddRequestHeader=X-Tenant,acme
        - AddResponseHeader=X-Genre,fanstasy
      - id: calculation-route
        uri: lb://CALCULATIONSERVICE
        predicates:
        - Path=/api/v1/cal/**
        filters:
        - AddRequestHeader=X-Tenant,acme
        - AddResponseHeader=X-Genre,fanstasy