spring:
  cloud:
    gateway:
      routes:
      - id: brand-route
        uri: lb://BRANDSERVICE
        predicates:
        - Path=/api/v1/brands/**
        filters:
        - AddRequestHeader=X-Tenant,acme
        - AddResponseHeader=X-Genre,fanstasy
      - id: product-route
        uri: lb://PRODUCTSERVICE
        predicates:
        - Path=/api/v1/products/**
        filters:
        - AddRequestHeader=X-Tenant,acme
        - AddResponseHeader=X-Genre,fanstasy