
server.port: 8083

spring:
    datasource:
        url: "jdbc:mysql://localhost:3306/calcdev"
        username: root
        password: "{cipher}9d559a5a044a898d7d7eb4950c82fddaedb01357448c2244cd4755c5644d2b0c4202404e95b7e820bca99aa47c8987ce"
#Hibernate
    jpa:
        properties:
            hibernate: 
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                format_sql: true
#Hibernate auto ddl
        hibernate: 
            ddl-auto: create
#JPA
        show-sql: false
        generate-ddl: false
    web:
        resources:
            cache:
                cachecontrol:
                    cache-public: false

logging:
    level:
        org:
            hibernate:
                SQL: debug
                type: debug


management.endpoints.web.exposure.include: "*"
